# Generated by Django 2.0.7 on 2018-08-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_quantity_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highscores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('besttime', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_Number',
        ),
    ]
