# Generated by Django 2.0.7 on 2018-08-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20180804_1502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Highscores',
            new_name='Highscore',
        ),
    ]
